### ISSUE TITLE
Most PSP games duplicated in the launcher after update

### ISSUE THREAD

**Issue by FrankEBailey** [jimbob4000/RetroFlow-Launcher#79] opened 2022-09-29 07:58 UTC
Hi! Fantastic piece of sofware, this, good job! I've hit a small snag though, after updating to the latest version of RetroFlow, most of the PSP games are duplicated. Is there something I need to do to remove these duplicates? I tried deleting the created bubbles from Adrenaline Bubble Manager but the duplicated games are still there. Any help will be most appreciated!

**Comment by jimbob4000** [comment] 2022-09-29 11:35
I'll have a look. 

If I can't replicate I may need you to go to the retroflow data folder and zip up the cache folder to send to me. 

I'll let you know if I need it.

**Comment by jimbob4000** [comment] 2022-09-29 19:14
I'm afraid I will need more info, as it's working fine for me.

Would you mind zipping up this folder and giving me a link to download it please?

`ux0:/data/RetroFlow/CACHE`

You can use [wetransfer.com](https://wetransfer.com/) or something similar to share the zip file.
I'll remove the download link from the comment once I have the file.

I'm hoping that I'll be able to see what the issue is by looking at the cache, but if you have any more info it would help.

Thanks

**Comment by jimbob4000** [comment] 2022-10-02 07:59
Temporarily closing issue until validated

**Closed** 2022-10-02 07:59 UTC
Labels: More info needed

**Comment by FrankEBailey** [comment] 2022-11-30 07:26
Hi, apologies for the delay on this, my Vita battery gave up the ghost and I finally got a new one.

Here's the CACHE folder zipped up as requested
https://drive.google.com/file/d/196A6OntJ8CLeMG-g9kpmnJIKFb80MVVs/view?usp=share_link

Here's [my screen](https://i.imgur.com/tNtmKy7.jpg) in RetroFlow PSP games showing the duplication. Note that not all titles are duplicated, but most are.

Thanks for taking a look into this for me.

**Comment by jimbob4000** [comment] 2022-11-30 09:09
Hi, can you update to the latest version of the app to see if it's still an issue?

The duplicates appear to be different files, do both of these exist for example:
```
ux0:/pspemu/ISO/A Space Shooter For 2 Bucks! [NPUZ00190].iso
ux0:/pspemu/ISO/A Space Shooter for 2 Bucks! (US) [NPUZ-00190].iso
```

Thanks

**Comment by FrankEBailey** [comment] 2022-11-30 12:28
As true as nuts, the duplicates are actually separate files! It seems something changed in the naming scheme of PSP titles from NPS Browser which resulted in duplicate ISOs being uploaded. I wouldn't have thought that could happen, but there you go. Apologies for barking up the wrong tree.

**Comment by jimbob4000** [comment] 2022-11-30 13:12
No problem
