### ISSUE TITLE
Retroflow v5.1.1 small issues

### ISSUE THREAD

**Issue by D33zN0tz84** [jimbob4000/RetroFlow-Launcher#105] opened 2023-01-19 20:11 UTC
Hi,

Sorry for my english, this is not my native language but I do my best :)
Its nice that the hide option has been added for homebrew apps. 
What I do expierience is that some homebrew is show 3 times and  its a grey box and when you push 1 off the 3 it crashes, it gets a weird black screen that showe a weird glitch and when you continue it i thinks starts broadcasting my
IP adress what looks like for ftp? i can not close this, i have to close the whole app.
and sometimes it just cycles to the retroflow startupscreen like you just came from youre vita live area.
I also can not hide these grey boxes, when i press trialgle it crashes on all grey boxes even it is a app or game that works perfect in the live area

Thx  for the good work :) I love this launcher for games.

![326407772_529748135887085_4582671962454132700_n](https://user-images.githubusercontent.com/123118743/213549312-0b7eb68f-cb7d-4e47-9af9-8d
![326366246_717541429945934_8344057001898266453_n](https://user-images.githubusercontent.com/123118743/213549328-3b9b53b8-3d87-4831-a118-8ca62fcde6f8.jpg)
5a7d1c9aa3.jpg)

**Comment by jimbob4000** [comment] 2023-01-19 20:28
Hi, can you try rescanning for new games, it may fix the issue.

For the grey games in the image, are they hidden?

The black screen with the IP address is a error screen, there should be a description of the error there, of you can send another picture of that screen, or type the message it may help me see what the problem is.

Thanks

**Comment by D33zN0tz84** [comment] 2023-01-19 20:35
Hey,

Rescanning does not solve the issue and this is not a app thats supposed to be hidden.
The hide app option works perfect. but not on the grey box. actualy the grey box you see is a game and it shows up grey and double with the same name and none of them work, they go to the retroflow startscreen like from the picture.
In the pictures this is what happens when i press triangle and when i press circle, a ftp server starts?? weird :)
![326324095_872770483842808_8857893491756919804_n](https://user-images.githubusercontent.com/123118743/213554111-d93a4729-24b7-4bfd-9d50-cb5077a1a889.jpg)
![326366246_717541429945934_8344057001898266453_n](https://user-images.githubusercontent.com/123118743/213554121-6f5c19d8-451d-4850-9c75-044cee0bcb9c.jpg)

**Comment by jimbob4000** [comment] 2023-01-19 20:58
Can you check your 'uxo:app' folder to see if the game is duplicated?

**Comment by D33zN0tz84** [comment] 2023-01-19 21:06
No it is not duplicated, i tested again with batteryfixer v3.0 and now the grey box is showing double with 2 times battery fixer name and the original icon is there also. when i delete it on the live area and rescan its gone. i think when i delete the other game and rescan, the boxes are gone to.

**Comment by jimbob4000** [comment] 2023-01-19 21:38
Okay, can you install this version of retroflow please:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

And also rename your hidden games file saved here:
`ux0:/data/RetroFlow/hidden_games.lua`

A new empty file will be created.

I've added some extra checks for hidden games, not sure if it will resolve the issue, but it might.

**Comment by jimbob4000** [comment] 2023-01-19 21:42
Please also rescan for new games

**Comment by D33zN0tz84** [comment] 2023-01-19 21:49
The new version you have send, still the same problem.
It has nothing  to do with the option to hide the app. maybe its just a conflict with gamefiles or app files...
95% of the homebrew games or apps do show up correctly. 

Grey cubes stay the same and also glitch and give the black screen with the error after triangle. and after X it goes to the retroflow startup screen.

https://user-images.githubusercontent.com/123118743/213569646-f04bb8a0-7cce-43ab-82db-c917fd472edd.mp4

**Comment by jimbob4000** [comment] 2023-01-19 21:55
The nightly app was installed, you deleted the hidden file and rescanned?

Is there anything unusual with that game, have you deleted, or played it recently, hidden the game at some point etc?
Anything that would make it exceptional?

I can't replicate the problem, so I;m running out of ideas

**Comment by D33zN0tz84** [comment] 2023-01-19 22:08
it had the same problem with the batteryfixer 3.0, dame cons same glitches and things... and startupscreen cycle.
i did not hide the  hurricane game. its the v0.9? there also is no newer version of this vpk.
4-5 apps games have this problem, the others i uninstalled because it are apps that i did not use anymore.
I tried re-installing batteryfixer 3.0 and the problem did appear again. i am running out of ideas to :)

**Comment by jimbob4000** [comment] 2023-01-19 22:20
Sorry, I'm out of ideas. 

I'm not sure if it's an issue with your setup or my app. 

If others report it too I may be able to figure out the problem with more information, but with the information I have at the moment, I can't see where the issue would be.

**Comment by jimbob4000** [comment] 2023-01-19 22:24
You could try installing Hexflow to see if the same problem occurs. 

https://github.com/VitaHEX-Games/HexFlow-Launcher/releases/tag/v0.5

Hexflow is the original app that I based retroflow on, it may help narrow down if it's a problem with the vita or the app.

**Comment by D33zN0tz84** [comment] 2023-01-19 22:27
ok now i am sure that it is the retroflow app. id dit this: i uninstalled hurricane, i restarted retroflow and rescanned. and another game that whas correct  the first time shows up with 2 grey boxes and the same crash effect. so what i did whas reinstalled hurricane, and now i cant find hurricane and yet another game has grey boxes... the one before the huricane install is bak again.

**Comment by D33zN0tz84** [comment] 2023-01-19 22:37
Sometimes when i trie to hide apps now because i deleted the file from the data folder... it has the same black screen from the first pictures :) i think its just my vita?

**Comment by D33zN0tz84** [comment] 2023-01-19 22:42
I did found hurricane again, it whas between the vita games... :D But iy has normal icon now and no grey boxes. Now the problem is Fallout, the original icon is there but also 2 grey boxes with the same name. This whas not there before

**Comment by jimbob4000** [comment] 2023-01-19 22:55
I've uploaded a video so you can see it working for me. 

https://streamable.com/70qm4o

Installed hurricane, rescanned and uninstalled without any grey icons. 

I'm afraid I'm going to close the issue, I'll reopen it if others report a problem.

**Comment by D33zN0tz84** [comment] 2023-01-19 22:57
Now i am renaming some vita games and every 3-4 games it also crashes... same black screen as the first pictures
ok thx for the effort. maybe it is my vita.

**Comment by jimbob4000** [comment] 2023-01-19 23:02
Sorry, for the time being I can't help, I'll reply back if something comes to light.

**Closed** 2023-01-19 23:03 UTC

**Comment by D33zN0tz84** [comment] 2023-01-19 23:05
Thx for the effort. Still love the app and how it looks.

**Comment by BlackSheepBoy69** [comment] 2023-01-22 17:48
Hello, please do these things and see if it fixes it:
1: install and run this program: https://github.com/cy33hc/copyicons ...then refresh cache in RetroFlow.

2: if that doesn't work, try using this mod of HexFlow (RetroFlow is also a mod of HexFlow) https://github.com/BlackSheepBoy69/HexFlow-Launcher-Unofficial-Custom/ ...while in the app hit the start button, then go to "refresh icons". This will also trigger a cache refresh in HexFlow Launcher Unofficial Custom so when you open the app again the icons should show up and likewise if you refresh the cache in RetroFlow.

I encountered this issue a lot and it might be related to "when you have a lot of apps on your Vita and you don't use folders, the icons don't get installed to your system right"

**Comment by D33zN0tz84** [comment] 2023-01-22 20:29
The first solution fixed the problem, the only app that shows up with these grey boxes is the copy icon app itself now but i deleted the app afrer scanning and now everything is ok.

Did you realy expierienced the same issue as me?

Thanks alot :-)

**Comment by D33zN0tz84** [comment] 2023-01-22 20:39
No sorry, I cheered to early. Now another app is shown up in grey,  1 the icon of the game itself and 2 extra grey spaces with the name of the game. and I can not hide them.  Second solution, i do not have the option to refresh icons...

**Comment by BlackSheepBoy69** [comment] 2023-01-22 21:10
Every time you install a new app you'll have to use either the copyicons app or "refresh icons" from inside HexFlow Laucher Custom. This is more of a Vita issue than a launcher issue, maybe someone will make a plugin to fix it?

So basicly try running copyicons again?

**Comment by BlackSheepBoy69** [comment] 2023-01-22 21:12
Also there is a secret feature: override Hurrican to "Vita" category and you can download a cover for it. Some of the most popular homebrews actually get downloadable covers while in the Vita category. Then you wouldn't need the default icon anyway.

**Comment by D33zN0tz84** [comment] 2023-01-22 21:21
The problem is that there are 3 icons with the same name, 1 icon of the 3 has the correct image of the game/app and the other 2 are grey boxes, with the same name, not its changed. its not "hurrican" anymore it is the game "this war of mine". Thats the weird thing. if install a new app and rescan in retroflow, the new app gets the problem. Just like installed the app "copyicons". after installing this app and running it, i rescanned in retroflow and the only app that  showed up with one picturicon and 2 grey whas "copyicons", so i think... ok lets uninstall "copyicons" and he problem is gone... but noooo now "this war of mine" has the tripple icon issue. Also when i want to hide the grey icons and i push triangle to get the option menu... it glitches and gives me restart and ftp option and freezes

**Comment by jimbob4000** [comment] 2023-01-22 21:27
Each time you delete an app in retroflow it's a good idea to rescan. 

Did you try Hexflow or Hexflow custom, to see if the icon problem is fixed with either of these launchers?

https://github.com/VitaHEX-Games/HexFlow-Launcher

https://github.com/BlackSheepBoy69/HexFlow-Launcher-Unofficial-Custom

**Comment by D33zN0tz84** [comment] 2023-01-22 21:30
The previous version of retroflow did not had this problem, but it also did not have the hide app option. in homebrew is this option realy nice because i only want to show the games and not all the stupid apps that or also on the vita :)

**Comment by jimbob4000** [comment] 2023-01-22 21:40
The last thing you can try is renaming the retroflow folder in ux0 data. 

This will effectively give you a fresh start. 

If that doesn't work I'm afraid you will need to either downgrade or live with the issue for the time being. 

I can't replicate the problem, so can't say when or if it will be fixed.

**Comment by BlackSheepBoy69** [comment] 2023-01-22 21:46
> The problem is that there are 3 icons with the same name, 1 icon of the 3 has the correct image of the game/app and the other 2 are grey boxes, with the same name, now its changed. its not "hurrican" anymore it is the game "this war of mine". Thats the weird thing. if install a new app and rescan in retroflow, the new app gets the problem. Just like installed the app "copyicons". after installing this app and running it, i rescanned in retroflow and the only app that showed up with one picturicon and 2 grey whas "copyicons", so i think... ok lets uninstall "copyicons" and he problem is gone... but noooo now "this war of mine" has the tripple icon issue. Also when i want to hide the grey icons and i push triangle to get the option menu... it glitches and gives me restart and ftp option and freezes

This is a lot of info and hard to understand but it seems like a combination of issues caused by RetroFlow "hide entry" that I don't understand, and issues related to you uninstalling apps and not refreshing cache in RetroFlow since if you turn "startup scan off" in RetroFlow so it can start faster, it won't magically register when you uninstalled an app.

**Comment by D33zN0tz84** [comment] 2023-01-22 23:13
Yeah, sorry its hard to understand. Let me show you in a video.  a video says a 1000 words :)

When I autoscan at startup... every time the apps i hide show up, i have to triangle in the settings to hide them again like i do in the video. I hide them again after a manual scan but it is the same as a startupscan.

Thx :) i hope its clear what i mean

https://user-images.githubusercontent.com/123118743/213945509-34a15100-85fb-4644-8c6c-8ca7bb000a11.mp4

**Comment by jimbob4000** [comment] 2023-01-23 00:01
Thanks for the video. 

I noticed a bug with hiding homebrew, not sure if it's the cause of you're issue, but will try to fix it and we can test again. 

Will let you know when a new vpk is ready. 

Thanks for your patience.

**Comment by D33zN0tz84** [comment] 2023-01-23 00:03
No worry, im not in a hurry :) thx

**Comment by BlackSheepBoy69** [comment] 2023-01-23 01:20
Oh yeah that makes it a lot more clear, seems like an issue with RetroFlow, whether related to "Hide Game" I'm not completely sure. This one might be harder to figure out.

While you wait for it to be fixed... If what you're trying to do is have a "homebrew" category with only actual games, and NO tools/utilities such as for example VitaShell... your best bet in RetroFlow might be to get a fresh start by deleting the "ux0:data/RetroFlow" folder so it can clear all the hidden games and all the settings, then just go in settings and hit "Hide Homebrews: ON" but for games that are homebrews that you want to keep, put them in the "Vita" category?

At least as a short term solution

...because although you are very helpful today, still it's not completely clear where in the code it glitches up and causes the issue and might take a little bit of time to fix.

**Comment by D33zN0tz84** [comment] 2023-01-23 19:20
Thankyou for youre time and effort :)

**Comment by jimbob4000** [comment] 2023-01-24 18:46
Hi again, 

I've applied some bug fixes to try and resolve the issue.

Please make sure you delete the following file:
`ux0:/data/RetroFlow/hidden_games.lua` 

Then delete this folder:
`ux0:/data/RetroFlow/CACHE`

Finally, install the new vpk from here:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

Let me know if the problem is fixed.

Thanks

**Comment by D33zN0tz84** [comment] 2023-01-24 18:58
I have tried the new version and did everything you asked for deleting file and folder and now it crashes instant after the bootscreen of retroflow, i get this screen
![327356464_740765277386367_2488411768468363051_n](https://user-images.githubusercontent.com/123118743/214383874-18824e37-af07-413b-a8c3-fe51d8e485d5.jpg)

**Comment by jimbob4000** [comment] 2023-01-24 19:23
Okay, really sorry about that, that error is for a new feature :)

I've fixed it and uploaded a v2 vpk for you to try:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/Nightly

**Comment by jimbob4000** [comment] 2023-01-24 19:41
Okay, that's one problem fixed.

The grey icon thing I'm not sure about.

If you are able to send me your cache folder in a zip file I can see if I can see anything unusual.
Also let me know which game had grey icons when you created the zip file.

**Comment by D33zN0tz84** [comment] 2023-01-24 19:50
Hey there, about the file I uploaded, rename .jpg to .rar (that whas the only way i could upload. :)

About the no crash, i just hided all the apps again and when i came about the 2 last apps i wanted to hide it gave me the scrash screen of the picture I send 2 messages back. and after rebooting retroflow de apps did hide, but it did gave the crashscreen


![CACHE](https://user-images.githubusercontent.com/123118743/214393793-843db43a-79ec-4d38-9370-8d58f57c81c8.jpg)

**Comment by jimbob4000** [comment] 2023-01-24 19:58
This War of Mine appears in three locations:

`ux0:/app/MODORU000`
`ux0:/app/TWOM00000`
`ux0:/app/NPOA00030`

Any ideas?

**Comment by D33zN0tz84** [comment] 2023-01-24 20:01
Hey

No actualy i don’t. Maybe it has something to do with that i tried different versions of the game installing and testing trial and error, modding the game with DLC’s and reinstalling versions and testing untill it worked…


Vriendelijke groeten,
Kind regards,

Kristof Vermeulen
***@***.***

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows

Van: ***@***.***>
Verzonden: dinsdag 24 januari 2023 20:58
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [jimbob4000/RetroFlow-Launcher] Retroflow v5.1.1 small issues (Issue #105)


This War of Mine appears in three locations:

ux0:/app/MODORU000
ux0:/app/TWOM00000
ux0:/app/NPOA00030

Any ideas?

**Comment by jimbob4000** [comment] 2023-01-24 20:08
Okay, that could be the problem.

Try opening the following sfo files in vitashell.
`ux0:/app/MODORU000//sce_sys/param.sfo`
`ux0:/app/NPOA00030//sce_sys/param.sfo`

If the title says "This War of Mine", then you will need to cleanup those app folders somehow.

**Comment by D33zN0tz84** [comment] 2023-01-24 20:16
I did something before you replied.
I uninstalled the game in the livearea, I deleted all 3 folders in the ux0:app folder, reinstalled the 
TWOM.vpk of the game and now there is 1 folder for the game.
I did a rescan in retroflow after the uninstalls so teh icons where gone, i rescanned after the new installation of the .vpk and now there is only one icon and everything is ok.

Where did you found this? So i can solve the problem in the future myself. 
Realy realy thankyou :)  You are realy good in what you do... i would have never found this.

**Comment by jimbob4000** [comment] 2023-01-24 20:22
That's okay, I'm glad it's finally resolved.

The hide app feature was a nightmare to code, so I wasn't sure if it was related to that.

I found the problem games by opening the `db_homebrews.lua` file from the cache folder and checking the 'game_path' for those problem games to see if they were duplicated, or if they were in different locations.

Thanks for your patience, it's been a difficult issue to fix, as there were two problems going on at once.

**Comment by D33zN0tz84** [comment] 2023-01-24 20:31
In that db_homebrew_lau where there other apps also dubble? 
the weird thing is that it changed, there whas always 1 game/app that 
had 3 icons, if uninstalled 1, it changed to another one.

The app/games that had the tripple icons where:
Batteryfixer 3.0
Dead space
Fallout
Half life

And now everythins is ok, I even installed batteryfixer 3.0 again and it 
remains having 1 icon. so i think it glitched out only with those 3 folders of 
twom for a reason affecting other game/app icons... realy realy weird

**Comment by D33zN0tz84** [comment] 2023-01-24 20:41
I think its mu fault, the grey icons and the useless folders, they did not uninstalled properly by uninstalling a not working vpk
I like to experiment and try new stuff and sometimes it glitches things out, like now with retroflow :)
If this problem shows up again on someones vita... and it will sooner or later... you will know the solution or they will read this Topic and figure out what to do.

**Comment by jimbob4000** [comment] 2023-01-24 20:42
That's okay :)

That was the only game that was duplicated in the db_homebrew.lua.
So there shouldn't be any more grey boxes hopefully.

The app can be frustrating for me too :)

**Comment by D33zN0tz84** [comment] 2023-01-24 20:44
I know nothing about coding... I do know how to f*ck things up :)
I realy love the app and the mod, its one of the most beautifull game launcher/library's to find.

**Comment by BlackSheepBoy69** [comment] 2023-01-24 23:25
@jimbob4000 several homebrews that have improperly formatted param.sfo files including: Modoru, Cook Serve Delicious, Flop Rocket, I was rebuilt... those apps when it scans them it puts literally any characters it feels like into the apptitle field after character # 10 and it messes up my and your cache systems (well I know it messes up mine at least, it creates new invalid entries in this way).

Create an experimental nightly using Rinne's latest Lua+ eboot (yes, even though it has the new bad apptitles). Just to check if this solves DeezNots84's issue. I can probably make a script to make apptitles be the way we like while still using the latest eboot but for now just test if it fixes this issue?

**Comment by jimbob4000** [comment] 2023-01-25 07:41
@BlackSheepBoy69 , I think it may be unrelated.

I installed Modoru, flop rocket and this war of mine, and there weren't any grey boxes, the apptile may be clipped for flop rocket, but you can rename it.

I think the issue was the user had a bad install for this war of mine, that game's sfo file was in three different locations:
ux0:/app/MODORU000
ux0:/app/TWOM00000
ux0:/app/NPOA00030

Thanks

**Comment by BlackSheepBoy69** [comment] 2023-01-25 22:41
Oh, they got it working? Cool!

**Comment by D33zN0tz84** [comment] 2023-01-25 22:43
Thanks allot :)
